---
abstract: 'Dancer Authentication, Security and Role-Based Access Control Framework!'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101241'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Authorize
recommends: {}
requires:
  DBD::Pg: 0
  DBD::SQLite: 0
  DBD::mysql: 0
  DBI: 0
  Dancer: 0
  Dancer::Plugin::Database: 0
version: 0.10
